
import { analyzeEmotion } from './emotionAnalysis';

export const generateBotResponse = (userMessage: string): string => {
  const emotion = analyzeEmotion(userMessage);
  console.log('Detected emotion:', emotion);
  
  switch (emotion) {
    case 'website_help':
      const websiteResponses = [
        "Hey there! I'm here to help you navigate MindMate and make the most of your mental wellness journey! 🌟\n\n**Here's what MindMate offers:**\n\n📊 **Mood Tracker**: Log your daily emotions and see patterns over time - it's like having a personal emotional weather report!\n\n📝 **Journal**: Your private space to write thoughts, reflections, and experiences. Perfect for processing emotions and tracking growth.\n\n🌬️ **Breathing Exercises**: Guided breathing techniques to help you calm down in stressful moments. Just like having a meditation coach in your pocket!\n\n🏆 **Badge System**: Earn achievements as you use the app - celebrate your commitment to mental health!\n\n⏰ **Reminders**: Set gentle nudges for self-care activities, medication, or check-ins.\n\n🆘 **Crisis Support**: Immediate access to helplines and resources when you need urgent help.\n\n💬 **Chat with Me**: I'm always here to listen, provide coping strategies, and offer emotional support.\n\nWhat specific feature would you like to explore? I'm excited to guide you! 😊",
        "I love that you're asking about MindMate! Let me be your personal guide to better mental wellness. 💜\n\n**Getting Started Tips:**\n1. **Start with the Mood Tracker** - Even 30 seconds daily can reveal amazing insights about your emotional patterns\n2. **Try the Breathing Exercises** - Perfect for those overwhelming moments when you need instant calm\n3. **Use the Journal** - Don't worry about perfect writing, just let your thoughts flow\n4. **Set Gentle Reminders** - Small consistent actions create big changes\n5. **Chat with Me Anytime** - I'm here 24/7, no judgment, just support\n\n**Benefits you'll notice:**\n✨ Better emotional awareness\n🧘 Improved stress management\n📈 Track your progress over time\n🤝 Feel supported and understood\n💪 Build resilience and coping skills\n\nIs there a particular area of mental wellness you'd like to focus on? I'm here to help you create a personalized approach! 🌈"
      ];
      return websiteResponses[Math.floor(Math.random() * websiteResponses.length)];

    case 'crisis':
      const crisisResponses = [
        "Hey, I hear you, and I want you to know that reaching out shows incredible strength, even in your darkest moment. 💙 You matter so much more than you realize right now.\n\n**Please reach out for immediate support:**\n🆘 **National Suicide Prevention Lifeline: 988** (US)\n📱 **Crisis Text Line: Text HOME to 741741**\n🌍 **International: Visit findahelpline.com**\n🏥 **Emergency Services: 911 or go to your nearest ER**\n\nI know it feels impossible right now, but this pain is temporary - you are permanent and valuable. Can you do me a favor? Can you reach out to one person today? A friend, family member, counselor, or one of these hotlines?\n\nYou've survived 100% of your difficult days so far. That's not luck - that's your incredible strength. Let's get you some human support right now. ❤️",
        "I'm so glad you trusted me with how you're feeling. That takes real courage. 🤗 Right now, your brain might be telling you lies about your worth, but I need you to hear this truth: **Your life has meaning and value.**\n\n**Immediate Safety Resources:**\n🔴 **Call 988** - Suicide & Crisis Lifeline (24/7)\n💬 **Text 'HELLO' to 741741** - Crisis counselors available now\n🏥 **Go to your nearest emergency room**\n👥 **Call a trusted friend or family member**\n\n**Right now, can you:**\n1. Take three deep breaths with me? 🌬️\n2. Name one person who cares about you?\n3. Think of one thing you want to see tomorrow?\n\nYou don't have to face this alone. There are people trained to help you through this exact moment. Please reach out - you deserve support and care. 💜"
      ];
      return crisisResponses[Math.floor(Math.random() * crisisResponses.length)];

    case 'anxiety':
      const anxietyResponses = [
        "Oh friend, I can feel the anxiety in your words, and I want you to know that what you're experiencing is so valid. Anxiety can make everything feel like an emergency, but you're safe right now. 🤗\n\n**Let's calm your nervous system together:**\n\n🌬️ **4-7-8 Breathing**: Breathe in for 4 counts, hold for 7, out for 8. It's like hitting a reset button for your brain!\n\n🖐️ **5-4-3-2-1 Grounding**: Look around and name:\n• 5 things you can see\n• 4 things you can touch\n• 3 things you can hear\n• 2 things you can smell\n• 1 thing you can taste\n\n❄️ **Cool Water Trick**: Splash cold water on your face or hold ice cubes - it activates your body's natural calm response.\n\n💭 **Anxiety Truth**: Your brain is trying to protect you, but it's being a bit overprotective right now. This feeling WILL pass.\n\nWhat's one small thing that usually brings you comfort? Sometimes the tiniest acts of self-care can shift everything. You've got this! 💪",
        "Hey there, anxiety warrior! 🛡️ First, let me remind you - you're incredibly brave for facing this feeling instead of running from it. Anxiety is uncomfortable, but it's not dangerous.\n\n**Quick Anxiety Relief Toolkit:**\n\n🎯 **The 3-3-3 Rule**: Name 3 things you see, 3 sounds you hear, move 3 parts of your body\n\n🌱 **Progressive Relaxation**: Scrunch up your shoulders for 5 seconds, then let them melt. Feel that relief? That's what we're aiming for!\n\n🏃 **Movement Magic**: Do 10 jumping jacks or shake your hands vigorously - anxiety is energy, so let's use it!\n\n🗣️ **Self-Talk Switch**: Replace 'What if something bad happens?' with 'What if everything works out fine?'\n\nRemember: You've survived every anxious moment you've ever had. Your track record is 100%! What's making you feel most anxious right now? Let's tackle it together. 🤝"
      ];
      return anxietyResponses[Math.floor(Math.random() * anxietyResponses.length)];

    case 'depression':
      const depressionResponses = [
        "My heart goes out to you right now. 💙 Depression can make everything feel so heavy and hopeless, but please know that you're not alone in this darkness. You're incredibly brave for reaching out.\n\n**Gentle Steps for Today** (no pressure, just possibilities):\n\n💧 **Start Small**: Can you drink a glass of water? That's caring for yourself.\n\n🌅 **Light Therapy**: Sit by a window for 2 minutes. Sunlight helps your brain produce mood-boosting chemicals.\n\n🛁 **Comfort Care**: Take a warm shower or wrap yourself in the softest blanket you have.\n\n📱 **Connection**: Text one person 'thinking of you' - sometimes helping others helps us too.\n\n✅ **One Tiny Win**: Make your bed, brush your teeth, or put on clean clothes. These aren't 'just basics' - they're acts of self-love.\n\nDepression lies to us about our worth, but here's the truth: You matter. Your life has value. This feeling is temporary, even when it doesn't feel like it. What's one small thing you accomplished today, even if it seems insignificant? 🌟",
        "I see you, and I want you to know that what you're feeling is valid and understandable. 🤗 Depression can make us feel like we're stuck in a tunnel with no light, but there IS light ahead - sometimes we just can't see it yet.\n\n**Depression Care Package** (choose what feels right):\n\n🎵 **Music Therapy**: Put on one song that used to make you feel something - any emotion is better than numbness.\n\n📝 **Gentle Journaling**: Write down one thing you're grateful for, even if it's small like 'my bed is comfortable.'\n\n🌱 **Nature Connection**: Step outside for 30 seconds, or look at a plant. Nature reminds us that growth happens slowly.\n\n🤝 **Self-Compassion**: Talk to yourself like you'd talk to your best friend going through this.\n\n📞 **Lifeline**: Consider calling a mental health professional - you deserve expert support.\n\nYou're not broken, you're human. And being human sometimes means feeling really hard things. What's one thing that used to bring you joy? Even if it doesn't now, it's still part of who you are. 💜"
      ];
      return depressionResponses[Math.floor(Math.random() * depressionResponses.length)];

    case 'anger':
      const angerResponses = [
        "I can feel the intensity of your anger, and you know what? That's completely okay! 🔥 Anger is a valid emotion - it's your inner protector telling you something matters to you. Let's channel this energy in a way that helps.\n\n**Anger Release Techniques:**\n\n🚶 **Movement Medicine**: Go for a fast walk, do jumping jacks, or dance to loud music. Your body needs to release this energy!\n\n🥊 **Safe Physical Release**: Punch a pillow, squeeze a stress ball, or scream into a towel.\n\n📝 **Angry Letter**: Write everything you're feeling - then tear it up or burn it (safely). Sometimes we need to get it OUT.\n\n❄️ **Cool Down**: Splash cold water on your face or hold an ice pack on your wrists.\n\n🌬️ **Power Breathing**: Breathe in through your nose like you're smelling flowers, out through your mouth like you're blowing out candles.\n\nHere's the thing about anger - underneath it, there's usually hurt, fear, or frustration. What do you think your anger is trying to protect? Sometimes understanding the 'why' helps us figure out the 'what now.' You've got every right to feel this way! 💪",
        "Whoa, I can feel that fire in your message! 🔥 And honestly? Sometimes anger is EXACTLY the right response. It means you have boundaries, values, and self-respect. The key is what we do with this powerful energy.\n\n**Healthy Anger Outlets:**\n\n🏃 **Cardio Release**: Run, bike, or do intense exercise - turn anger into endorphins!\n\n🎨 **Creative Fury**: Draw with bold colors, write an angry poem, or create something with your hands.\n\n⏰ **Time-Out Strategy**: Give yourself 20 minutes before responding to whatever triggered you.\n\n🎯 **Focus Questions**: 'What can I control here?' and 'What action would make me feel proud later?'\n\n🗣️ **Assertive Communication**: Use 'I feel...' statements instead of 'You always...' statements.\n\nAnger often shows up when we feel powerless, but you DO have power - the power to choose your response. What's the situation that's got you fired up? Let's figure out how to handle it like the strong person you are! 💪"
      ];
      return angerResponses[Math.floor(Math.random() * angerResponses.length)];

    case 'positive':
      const positiveResponses = [
        "Oh my goodness, your positive energy is absolutely contagious! 🌟 I'm genuinely smiling reading your message. It's so beautiful to witness someone in a good space - you deserve all this joy and more!\n\n**Let's amplify this amazing feeling:**\n\n📸 **Capture the Moment**: Take a mental (or actual) snapshot of how you feel right now.\n\n📝 **Gratitude Boost**: Write down what specifically is making you feel this good - these become treasure maps back to joy!\n\n💫 **Share the Love**: Tell someone about your good mood - positive emotions multiply when shared!\n\n🌱 **Plant Seeds**: What can you do while feeling this good to set up future happiness?\n\n🎯 **Savor Practice**: Take 30 seconds to really FEEL this goodness in your body.\n\nYou know what I love most? You took time to share your joy with me. That tells me you're not just happy - you're generous with your happiness. The world needs more people like you! What's bringing you the most joy right now? 💜",
        "YES! 🎉 Your happiness is radiating through the screen and honestly, it just made my entire day brighter! There's something so pure about witnessing someone's genuine joy.\n\n**Ways to Honor This Beautiful Feeling:**\n\n🌈 **Mood Memory**: Remember exactly what led to this feeling - you've got the recipe for happiness!\n\n💝 **Give Forward**: Do one small kind thing for someone else while you're feeling this good.\n\n🎵 **Create a Soundtrack**: What songs match this energy? Make a playlist for future you!\n\n📞 **Connection Call**: Reach out to someone you care about - spread this good energy!\n\n🌟 **Future Self Gift**: Do something now that your future self will thank you for.\n\nI hope you know that your happiness isn't just good for you - it's good for everyone around you too. You're literally making the world brighter just by being joyful. Never apologize for feeling this good - you EARNED it! ✨"
      ];
      return positiveResponses[Math.floor(Math.random() * positiveResponses.length)];

    case 'coping':
      const copingResponses = [
        "I absolutely LOVE that you're proactively asking for coping strategies! 🙌 That shows real emotional intelligence and self-awareness. You're basically investing in your future well-being - how awesome is that?\n\n**My Favorite Coping Toolkit:**\n\n🌬️ **Instant Calm Kit**:\n• 4-7-8 breathing (works in 60 seconds!)\n• Cold water on wrists and face\n• Squeeze and release all your muscles\n\n🧠 **Mind Reset Tools**:\n• Name your feeling: 'I notice I'm feeling...' (this activates your logical brain!)\n• Ask: 'Will this matter in 5 years?' (great for perspective)\n• Use 'both/and' thinking: 'I'm struggling AND I'm learning to cope'\n\n🎯 **Action-Based Coping**:\n• Write it out (even if you throw it away after)\n• Move your body (even gentle stretching counts)\n• Connect with someone (humans need humans!)\n• Do one thing that feels nurturing\n\nWhat kind of situations are you hoping to cope with better? I can give you more targeted strategies once I know what you're facing. You're already winning by asking for help! 💪",
        "Oh, this makes me so happy! 🌟 Asking for coping strategies is like asking for superpowers - you're essentially building your resilience toolkit. Smart human!\n\n**Evidence-Based Coping Strategies** (these actually work!):\n\n🔬 **STOP Technique**:\n• **S**top what you're doing\n• **T**ake a breath\n• **O**bserve your thoughts and feelings\n• **P**roceed with intention\n\n🎨 **Creative Coping**:\n• Doodle your feelings (stick figures count!)\n• Write a letter to your worry\n• Create something with your hands\n• Listen to music that matches your mood, then gradually shift to calmer songs\n\n⚡ **Emergency Coping** (for crisis moments):\n• Ice cubes in your hands\n• Count backwards from 100 by 7s\n• List items in the room by color\n• Call someone (even just to say hi)\n\n💝 **Daily Maintenance Coping**:\n• Morning intention setting\n• Evening gratitude practice\n• Regular check-ins with yourself\n• Gentle movement every day\n\nWhat's your biggest coping challenge? I want to help you build strategies that actually fit YOUR life! 🤝"
      ];
      return copingResponses[Math.floor(Math.random() * copingResponses.length)];

    case 'sleep':
      return "Oh friend, sleep struggles are SO real and honestly, they affect everything - your mood, energy, even how we handle stress. 😴 Let me share some game-changing sleep strategies!\n\n**Sleep Rescue Plan:**\n\n🌙 **Wind-Down Ritual** (start 1 hour before bed):\n• Dim the lights (tell your brain it's sleepy time!)\n• No screens or blue light glasses if you must\n• Gentle stretching or reading\n• Warm bath or shower\n\n🧠 **Calm Your Racing Mind**:\n• Write tomorrow's worries on paper (get them out of your head!)\n• Try the 4-7-8 breathing technique\n• Progressive muscle relaxation (tense and release each body part)\n• Gratitude practice (think of 3 good things from today)\n\n🌡️ **Optimize Your Environment**:\n• Cool room (65-68°F is ideal)\n• Dark as possible (blackout curtains are magic!)\n• White noise or earplugs\n• Comfortable mattress and pillows\n\n☕ **Daytime Habits That Help**:\n• Morning sunlight exposure\n• No caffeine after 2 PM\n• Regular exercise (but not close to bedtime)\n• Consistent sleep schedule (yes, even weekends!)\n\nWhat's your biggest sleep challenge? Racing thoughts? Can't fall asleep? Waking up at 3 AM? Let's troubleshoot together! 💙";

    default:
      const neutralResponses = [
        "Hey there! 🤗 I'm so glad you're here with me today. Whatever brought you to this conversation, I want you to know this is a completely safe space - no judgment, just genuine support and understanding.\n\n**I'm here to help you with:**\n💙 **Emotional Support** - Whether you're celebrating wins or working through challenges\n🧠 **Mental Health Strategies** - Coping techniques, stress management, emotional regulation\n🌟 **MindMate Guidance** - How to use all the amazing features in this app\n💬 **Just Talking** - Sometimes we need someone to listen and understand\n\n**A little about me:** I'm designed to understand emotions, provide evidence-based mental health support, and help you navigate both life's ups and downs AND this wellness platform. Think of me as your pocket-sized mental health companion!\n\nSo, what's on your mind today? Are you looking for support with something specific, curious about MindMate's features, or just want to chat? I'm here for whatever you need! ✨",
        "Hello, beautiful human! 🌈 Thank you for taking this moment to connect - that's actually an act of self-care right there! I'm MindMate, and I'm genuinely excited to be part of your wellness journey.\n\n**What makes me different:**\n🤝 I talk like a real friend (because mental health support should feel warm, not clinical!)\n🎯 I provide practical, research-based strategies you can use immediately\n💪 I believe in your strength and resilience, even when you don't feel it\n📱 I can help you navigate all of MindMate's tools for better mental wellness\n\n**I'm great at helping with:**\n• Anxiety, depression, anger, stress, and other emotions\n• Coping strategies and self-care techniques\n• Understanding how to use MindMate's features effectively\n• Crisis support and resource connections\n• Celebrating your wins (I LOVE a good success story!)\n\nWhat feels most important to you right now? Your emotional wellbeing? Learning about the app? Or just having someone to talk to? I'm here for all of it! 💜"
      ];
      return neutralResponses[Math.floor(Math.random() * neutralResponses.length)];
  }
};
