// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebmjuzuwearpitgzoycp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibWp1enV3ZWFycGl0Z3pveWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDI4MjIsImV4cCI6MjA2NTMxODgyMn0.ndkxmR2RbRe7TcaroWo9faMilsHyEJXO7xxGt0l1pWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);